# dll
dlopen

# il2cpp_meta/Init
il2cpp::vm::Runtime::Init

# il2cpp_meta/il2cpp_codegen_initialize_runtime_metadata
il2cpp_codegen_initialize_runtime_metadata

# il2cpp_meta/GlobalMetadata
il2cpp::vm::GlobalMetadata::

# il2cpp_meta/ClassInit
il2cpp::vm::Class::Init

# il2cpp_meta/ClassSetupMethods
Class::SetupMethods

# fsui
UIManager
HitTextControl

# hybridclr/trasform
HiTransform::Transform

# hybridclr/runtime
LoadHotfix

#battle
ClientDR::
BattleManager::

#il2cpp/table
ConfigManager

# il2cpp/managed
GC_gcj_vector_malloc
Object::NewAllocSpecific
Object::NewPtrFree
Object::Allocate
Object::AllocatePtrFree
Object::AllocateSpec
GC_alloc

#RecastNavES
RecastNavES

# unity3d/Shader
Shader
CreateGpuProgram
CompileProgramImpl

# unity3d/gpu
GfxDevice

# unity3d/init
UnityInitApplication

# unity3d/GarbageCollect
GarbageCollect

# unity3d/assetbundle
AssetBundleLoadFromFile

# unity3d/Animation
AnimationClip
Animator

# unity3d/TypeTree
TypeTree


# unity3d/Mesh
Mesh

# unity3d/Material
Material

# unity3d/PreloadManager
PreloadManager

# sdk/crashsight
attachmentForException

# unity3d/font
FreeType

# unity3d/asset
MyResourceManager

# hybridclr/other
hybridclr

# unity3d/other
Unity

# sdk/msdk
MSDK

# il2cpp/other
il2cpp
